"""make_index.py — build packs.json (what the Smart Translator app downloads) from components.json + the files in dist/.

    python make_index.py            # writes packs.json; every component's asset must be in dist/
    python make_index.py --check    # verifies packs.json against dist/ (sizes + sha256), exit 1 on any mismatch

Adding a pack: put the file in dist/, add an entry to components.json (id, kind asr|vad, title, languages, asset, upstream,
licence, and for an archive the `keep` list), run this script, commit packs.json, then upload the asset to the release
named by `release_tag`:   gh release upload <release_tag> dist/<asset> --repo Hemues/smart-translator-languages
The app reads the index from the repository's main branch (raw URL), so a new pack is live for everyone as soon as both
the asset is uploaded and packs.json is pushed — no app update.
"""
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build() -> dict:
    meta = json.loads((ROOT / "components.json").read_text(encoding="utf-8"))
    out = []
    for c in meta["components"]:
        asset = DIST / c["asset"]
        if not asset.is_file():
            sys.exit(f"missing dist/{c['asset']} — put the file in dist/ first")
        # a component may live in its own release (voices-v1 for the voices); the top-level tag is the default
        base = meta["release_base"].rstrip("/") + "/" + c.get("release_tag", meta["release_tag"])
        entry = {k: c[k] for k in ("id", "kind", "engine", "title", "language", "voice", "gender", "quality", "languages") if k in c}
        entry["bytes"] = asset.stat().st_size
        entry["sha256"] = sha256(asset)
        entry["urls"] = [f"{base}/{c['asset']}"] + ([c["upstream"]] if c.get("upstream") else [])
        for k in ("licence", "licence_url", "archive", "keep", "file", "dir"):
            if k in c:
                entry[k] = c[k]
        out.append(entry)
        print(f"{c['id']}: {entry['bytes']:,} bytes  sha256 {entry['sha256'][:16]}…  ({len(entry['urls'])} url(s))")
    return {
        "index_version": meta.get("index_version", 1),
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "min_app_version": 2,
        "notes": "Smart Translator speech-pack index (app docs/04 §3). Generated by make_index.py from components.json + dist/. "
                 "The app tries urls in order and verifies sha256 over the whole download whichever source answered.",
        "components": out,
    }


def check() -> int:
    idx = json.loads((ROOT / "packs.json").read_text(encoding="utf-8"))
    bad = 0
    for c in idx["components"]:
        name = c["urls"][0].rsplit("/", 1)[-1]
        p = DIST / name
        if not p.is_file():
            print(f"MISSING dist/{name}"); bad += 1; continue
        ok = p.stat().st_size == c["bytes"] and sha256(p) == c["sha256"]
        print(f"{'OK ' if ok else 'BAD'} {c['id']}  {p.stat().st_size:,} bytes")
        bad += 0 if ok else 1
    return 1 if bad else 0


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(check())
    index = build()
    (ROOT / "packs.json").write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"packs.json written with {len(index['components'])} component(s)")
